# Generated by Django 4.1.9 on 2023-05-22 16:14

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_user_account_type_user_first_name_user_last_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
        ),
    ]
