# Generated by Django 4.1.9 on 2023-05-22 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("extrafee", "0001_initial"),
        ("processingtask", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extrafee",
            name="processing_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="processingtask.processingtask",
                verbose_name="Processing Task",
            ),
        ),
        migrations.AddField(
            model_name="extrafee",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="Product",
            ),
        ),
    ]
