# Generated by Django 4.1.8 on 2023-04-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
    ]
