# Generated by Django 4.1.9 on 2023-05-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("installment", "0002_installmentline_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installmentline",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="installmentline",
            name="installment_number",
            field=models.IntegerField(default=1, verbose_name="Installment Number"),
        ),
    ]
