# Generated by Django 4.1.9 on 2023-05-22 16:14

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_type",
            field=model_utils.fields.StatusField(
                choices=[
                    ("PROVIDER", "Platform Provider"),
                    ("STAFF", "Platform Staff"),
                    ("SUPPLIER", "Supplier"),
                    ("CUSTOMER", "Customer"),
                ],
                default="PROVIDER",
                max_length=100,
                no_check_for_status=True,
                verbose_name="Account Type",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="last name"),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[("ONLINE", "Online"), ("OFFLINE", "Offline")],
                default="ONLINE",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="status_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tnc",
            field=models.BooleanField(default=False, verbose_name="Terms and conditions"),
        ),
    ]
