# Generated by Django 4.1.8 on 2023-04-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tnc",
            field=models.BooleanField(default=False, verbose_name="Terms and conditions"),
        ),
    ]
