# Generated by Django 4.1.8 on 2023-05-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_account_type_user_status_user_status_changed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tnc",
            field=models.BooleanField(default=False, verbose_name="Terms and conditions"),
        ),
    ]
