# Generated by Django 4.1.8 on 2023-05-20 06:27

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_account_type_user_status_user_status_changed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=model_utils.fields.StatusField(
                choices=[
                    ("PROVIDER", "Platform Provider"),
                    ("STAFF", "Platform Staff"),
                    ("SUPPLIER", "Supplier"),
                    ("CUSTOMER", "Customer"),
                ],
                default="PROVIDER",
                max_length=100,
                no_check_for_status=True,
                verbose_name="Account Type",
            ),
        ),
    ]
