# Generated by Django 4.1.8 on 2023-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tnc",
            field=models.BooleanField(default=False, verbose_name="Terms and conditions"),
        ),
    ]
