# Generated by Django 4.1.9 on 2023-05-22 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("category", "0001_initial"),
        ("level", "0001_initial"),
        ("sku", "0001_initial"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_levels",
                        to="category.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_levels",
                        to="level.level",
                        verbose_name="Level",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_levels",
                        to="sku.sku",
                        verbose_name="SKU",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="supplier.supplier", verbose_name="Supplier"
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Level",
                "verbose_name_plural": "Supplier Levels",
                "db_table": "supplier_level",
            },
        ),
    ]
