# Generated by Django 4.1.8 on 2023-05-21 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoiceline",
            old_name="base_content_type",
            new_name="content_type",
        ),
        migrations.RenameField(
            model_name="invoiceline",
            old_name="base_object_id",
            new_name="object_id",
        ),
    ]
