# Generated by Django 4.1.9 on 2023-05-24 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlugResolve",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(max_length=255, unique=True, verbose_name="Slug")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Slug Resolve",
                "verbose_name_plural": "Slug Resolves",
                "db_table": "cms_slug_resolve",
            },
        ),
    ]
