# Generated by Django 4.1.8 on 2023-05-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
        ("order", "0002_order_value_added_service_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLineProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField(default=1, verbose_name="Quantity")),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.orderline", verbose_name="Order Line"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="product.product", verbose_name="Product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Line Product",
                "verbose_name_plural": "Order Line Products",
                "db_table": "order_order_line_product",
            },
        ),
        migrations.AddField(
            model_name="orderline",
            name="products",
            field=models.ManyToManyField(through="order.OrderLineProduct", to="product.product"),
        ),
    ]
