# Generated by Django 4.1.8 on 2023-05-20 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
        ("processingtask", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingtask",
            name="performed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Performed At"),
        ),
        migrations.AddField(
            model_name="processingtask",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="staff.staff",
                verbose_name="Performed By",
            ),
        ),
    ]
