# Generated by Django 4.1.8 on 2023-05-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("processingtask", "0002_processingtask_performed_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processingtask",
            name="product",
        ),
        migrations.AddField(
            model_name="processingtask",
            name="content_type",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processingtask",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
