# Generated by Django 4.1.9 on 2023-05-22 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("uom", "0001_initial"),
        ("sku", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UOMConversion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("ratio", models.PositiveBigIntegerField(default=0, verbose_name="Ratio")),
                ("base_uom_ratio", models.PositiveBigIntegerField(default=0, verbose_name="Base UOM Ratio")),
                (
                    "child_uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_child_conversions",
                        to="uom.uom",
                        verbose_name="Child UOM",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_last_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last modified by",
                    ),
                ),
                (
                    "parent_uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_parent_conversions",
                        to="uom.uom",
                        verbose_name="Parent UOM",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions",
                        to="sku.sku",
                        verbose_name="SKU",
                    ),
                ),
            ],
            options={
                "verbose_name": "UOM Conversion",
                "verbose_name_plural": "UOM Conversions",
                "db_table": "master_data_uom_conversion",
            },
        ),
    ]
