# Generated by Django 4.1.9 on 2023-05-23 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("invoice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("receiving", "Receiving"),
                            ("received", "Received"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("payment_number", models.IntegerField(default=1, verbose_name="Payment Number")),
                (
                    "transaction_code",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Transaction Code"),
                ),
                ("expiration_date", models.DateField(blank=True, null=True, verbose_name="Expiration Date")),
                ("description", models.CharField(blank=True, max_length=2550, null=True, verbose_name="Description")),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name="Total Amount"),
                ),
                (
                    "received_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name="Received Amount"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="invoice.invoice",
                        verbose_name="Invoice",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_last_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "finance_payment",
            },
        ),
        migrations.CreateModel(
            name="PaymentLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("received", "Received"), ("accepted", "Accepted"), ("rejected", "Rejected")],
                        default="received",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                (
                    "recipient",
                    models.CharField(blank=True, default="", max_length=2550, verbose_name="Recipient Code"),
                ),
                ("description", models.CharField(blank=True, default="", max_length=2550, verbose_name="Description")),
                ("amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name="Amount")),
                ("payment_date", models.DateField(blank=True, null=True, verbose_name="Payment Date")),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_lines",
                        to="payment.payment",
                        verbose_name="Payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Line",
                "verbose_name_plural": "Payment Lines",
                "db_table": "finance_payment_line",
            },
        ),
    ]
