# Generated by Django 4.1.9 on 2023-05-22 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("category", "0001_initial"),
        ("sku", "0001_initial"),
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "favorite_category",
                    models.ManyToManyField(
                        blank=True,
                        related_name="suppliers",
                        to="category.category",
                        verbose_name="Favorite Categories",
                    ),
                ),
                (
                    "favorite_sku",
                    models.ManyToManyField(
                        blank=True, related_name="suppliers", to="sku.sku", verbose_name="Favorite SKUs"
                    ),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplier.supplier",
                        verbose_name="Supplier Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Profile",
                "verbose_name_plural": "Supplier Profiles",
                "db_table": "supplier_profile",
            },
        ),
    ]
