# Generated by Django 4.1.8 on 2023-05-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
        ("sku", "0003_alter_sku_markup"),
        ("supplierprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierprofile",
            name="favorite_category",
            field=models.ManyToManyField(
                blank=True, related_name="suppliers", to="category.category", verbose_name="Favorite Categories"
            ),
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="favorite_sku",
            field=models.ManyToManyField(
                blank=True, related_name="suppliers", to="sku.sku", verbose_name="Favorite SKUs"
            ),
        ),
    ]
