# Generated by Django 4.1.8 on 2023-05-14 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uom",
            name="base_uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="uom.uom",
                verbose_name="Base UOM",
            ),
        ),
    ]
