# Generated by Django 4.1.8 on 2023-05-20 06:31

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0004_alter_user_account_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staffs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
        ),
    ]
