# Generated by Django 4.1.8 on 2023-05-18 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("extrafeetype", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraFeePriceList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True, verbose_name="Unique Code")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("description", models.CharField(blank=True, max_length=255, null=True, verbose_name="Description")),
                ("effective_date", models.DateField(verbose_name="Effective Date")),
                ("expiry_date", models.DateField(verbose_name="Expiry Date")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_fee_price_lists",
                        to="customer.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_last_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extra Fee Price List",
                "verbose_name_plural": "Extra Fee Price Lists",
                "db_table": "master_data_extra_fee_price_list",
            },
        ),
        migrations.CreateModel(
            name="ExtraFeePriceLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "calculate_type",
                    models.CharField(
                        choices=[
                            ("FIXED_AMOUNT", "Fixed Amount"),
                            ("MULTIPLY_QUANTITY", "Multiply Quantity"),
                            ("PERCENTAGE", "Percentage"),
                        ],
                        default="FIXED_AMOUNT",
                        max_length=20,
                        verbose_name="Calculate Type",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name="Price"),
                ),
                ("unit_percentage", models.FloatField(blank=True, null=True, verbose_name="Percentage")),
                (
                    "extra_fee_price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_fee_price_lines",
                        to="extrafeepricelist.extrafeepricelist",
                        verbose_name="Extra Fee Price List",
                    ),
                ),
                (
                    "extra_fee_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="extrafeetype.extrafeetype",
                        verbose_name="Extra Fee Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extra Fee Price Line",
                "verbose_name_plural": "Extra Fee Price Lines",
                "db_table": "master_data_extra_fee_price_line",
            },
        ),
    ]
