# Generated by Django 4.1.8 on 2023-05-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rank", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="discount",
            field=models.FloatField(default=0, verbose_name="Discount"),
        ),
    ]
