# Generated by Django 4.1.8 on 2023-05-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sku", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sku",
            name="quantity_type",
            field=models.CharField(
                choices=[("SEPARATE", "Separate"), ("UNITE", "Unite")],
                default="SEPARATE",
                max_length=255,
                verbose_name="Quantity Type",
            ),
        ),
    ]
