# Generated by Django 4.1.8 on 2023-05-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sku", "0002_sku_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sku",
            name="markup",
            field=models.FloatField(default=1, verbose_name="Markup"),
        ),
    ]
